version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      NODEMAILER_EMAIL: ${NODEMAILER_EMAIL}
      NODEMAILER_PASSWORD: ${NODEMAILER_PASSWORD}
      STRIPE_PRIVATE_KEY: ${STRIPE_PRIVATE_KEY}
    command: npm run dev

volumes:
  postgres_data: