name: CI/CD Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: Install dependencies
              run: npm install && npm run build

            - name: Run tests
              run: npm test

    deploy:
        needs: build # Ensures this job runs only after `build` completes successfully
        runs-on: ubuntu-latest
        permissions:
            deployments: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to Render
              uses: JorgeLNJunior/render-deploy@v1.4.4
              with:
                  service_id: ${{ secrets.RENDER_SERVICE_ID }}
                  api_key: ${{ secrets.RENDER_API_KEY }}
                  github_deployment: true
                  deployment_environment: "production"
                  github_token: ${{ secrets.TOKEN_KEY }}
