name: CI/CD Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18.x"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              continue-on-error: false
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
                  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

              run: npm test
            - name: Confirm Build Success
              run: echo "Build job completed successfully"

    deploy:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            deployments: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to Render
              uses: JorgeLNJunior/render-deploy@v1.4.4
              with:
                  service_id: ${{ secrets.RENDER_SERVICE_ID }}
                  api_key: ${{ secrets.RENDER_API_KEY }}
                  github_deployment: true
                  deployment_environment: "production"
                  github_token: ${{ secrets.TOKEN_KEY }}
